In [2]:
import os
import sys

project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root not in sys.path:
    sys.path.append(project_root)

In [3]:
from lib.data_load import load_data

df = await load_data()
print(f"\n{'CONCATENATED':<62} {df.shape[0]:>6,} rows x {df.shape[1]} cols")
df.sample(10)

1429_1.csv                                                     34,660 rows
Datafiniti_Amazon_Consumer_Reviews_of_Amazon_Products.csv       5,000 rows
Datafiniti_Amazon_Consumer_Reviews_of_Amazon_Products_May19.csv 28,332 rows

CONCATENATED                                                   67,992 rows x 28 cols

,id,name,asins,brand,categories,keys,manufacturer,reviews.date,reviews.dateAdded,reviews.dateSeen,...,reviews.userCity,reviews.userProvince,reviews.username,source_file,dateAdded,dateUpdated,primaryCategories,imageURLs,manufacturerNumber,sourceURLs
43569,AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,"B00QWO9P0O,B00LH3DMUO",Amazonbasics,"AA,AAA,Health,Electronics,Health & Household,C...","amazonbasics/hl002619,amazonbasicsaaaperforman...",AmazonBasics,2016-01-23T00:00:00.000Z,NaN,2017-08-28T00:00:00Z,...,NaN,NaN,Byschaufdea,Datafiniti_Amazon_Consumer_Reviews_of_Amazon_P...,2015-10-30T08:59:32Z,2019-04-25T09:08:16Z,Health & Beauty,https://images-na.ssl-images-amazon.com/images...,HL-002619,"https://www.barcodable.com/upc/841710106442,ht..."
11344,AVphgVaX1cnluZ0-DR74,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B018Y229OU,Amazon,"Fire Tablets,Tablets,Computers & Tablets,All T...",firetablet7displaywifi8gbincludesspecialoffers...,Amazon,2016-01-09T00:00:00.000Z,2017-05-21T02:34:08Z,"2017-04-30T00:18:00.000Z,2017-06-07T08:13:00.000Z",...,NaN,NaN,Rudedoogg43,1429_1.csv,NaN,NaN,NaN,NaN,NaN,NaN
24587,AVpfl8cLLJeJML43AE3S,"Echo (White),,,\r\nEcho (White),,,","B00L9EPT8O,B01E6AO69U",Amazon,"Stereos,Remote Controls,Amazon Echo,Audio Dock...","echowhite/263039693056,echowhite/152558276095,...",Amazon,2016-11-16T00:00:00.000Z,NaN,"2017-09-28T00:00:00Z,2017-09-08T00:00:00Z,2017...",...,NaN,NaN,Joncman,1429_1.csv,NaN,NaN,NaN,NaN,NaN,NaN
6959,AVphgVaX1cnluZ0-DR74,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",B018Y229OU,Amazon,"Fire Tablets,Tablets,Computers & Tablets,All T...",firetablet7displaywifi8gbincludesspecialoffers...,Amazon,2016-11-30T00:00:00.000Z,2017-05-21T01:20:16Z,"2017-04-30T00:08:00.000Z,2017-06-07T08:15:00.000Z",...,NaN,NaN,George,1429_1.csv,NaN,NaN,NaN,NaN,NaN,NaN
44460,AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,"B00QWO9P0O,B00LH3DMUO",Amazonbasics,"AA,AAA,Health,Electronics,Health & Household,C...","amazonbasics/hl002619,amazonbasicsaaaperforman...",AmazonBasics,2016-08-18T00:00:00.000Z,NaN,2017-08-28T00:00:00Z,...,NaN,NaN,ByMorgan8407,Datafiniti_Amazon_Consumer_Reviews_of_Amazon_P...,2015-10-30T08:59:32Z,2019-04-25T09:08:16Z,Health & Beauty,https://images-na.ssl-images-amazon.com/images...,HL-002619,"https://www.barcodable.com/upc/841710106442,ht..."
62923,AVph0EeEilAPnD_x9myq,"Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16...",B018Y22C2Y,Amazon,"Computers,Fire Tablets,Electronics Features,Co...",amazonfirekidsedition16gb5thgen2015releaseblue...,Amazon,2017-02-04T00:00:00.000Z,NaN,"2017-04-26T00:00:00Z,2017-06-04T00:00:00Z,2017...",...,NaN,NaN,Drea,Datafiniti_Amazon_Consumer_Reviews_of_Amazon_P...,2017-01-11T06:58:33Z,2019-02-25T02:05:06Z,Electronics,https://pisces.bbystatic.com/image2/BestBuy_US...,53-004755,http://reviews.bestbuy.com/3545/5026000/review...
53840,AVqVGWQDv8e3D1O-ldFr,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...","B018SZT3BK,B01AHB9CN2",Amazon,"Fire Tablets,Computers/Tablets & Networking,El...",amazonfirehd88intablet16gbblackb018szt3bk6thge...,Amazon,2017-01-01T00:00:00.000Z,NaN,"2017-04-30T00:00:00Z,2017-06-07T00:00:00Z,2017...",...,NaN,NaN,000G,Datafiniti_Amazon_Consumer_Reviews_of_Amazon_P...,2017-03-03T16:55:53Z,2019-03-09T07:13:43Z,Electronics,http://i.ebayimg.com/thumbs/images/g/9DAAAOSwE...,53-004484,http://reviews.bestbuy.com/3545/5620406/review...
65775,AVqkIhxunnc1JgDc3kg_,"Fire HD 8 Tablet with Alexa, 8 HD Display, 16 ...",B018T075DC,Amazon,"Fire Tablets,Tablets,All Tablets,Amazon Tablet...","amazon/b018t075dc,firehd8tabletwithalexa8hddis...",Amazon,2016-12-15T00:00:00.000Z,NaN,"2017-04-30T00:00:00Z,2017-06-07T00:00:00Z",...,NaN,NaN,Matt,Datafiniti_Amazon_Consumer_Reviews_of_Amazon_P...,2017-03-06T14:59:43Z,2019-02-23T02:49:38Z,Electronics,https://www.upccodesearch.com/images/barcode/0...,53-004485,http://reviews.bestbuy.com/3545/5620410/review...
15884,AVqVGWLKnnc1JgDc3jF1,"Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16...",B018Y23MNM,Amazon,"Tablets,Fire Tablets,Computers & Tablets,All T...",firekidseditiontablet7displaywifi16gbgreenkidp...,Amazon,2017-01-06T00:00:00.000Z,2017-04-03T18:32:34Z,"2017-03-31T09:12:26.371Z,2017-06-04T02:16:48.3...",...,NaN,NaN,Bradman,1429_1.csv,NaN,NaN,NaN,NaN,NaN,NaN
14989,AVpjEN4jLJeJML43rpUe,Brand New Amazon Kindle Fire 16gb 7 Ips Displa...,B018Y225IA,Amazon,"Computers/Tablets & Networking,Tablets & eBook...","841667103143,0841667103143,brandnewamazonkindl...",Amazon,2016-12-07T00:00:00.000Z,NaN,"2017-08-27T00:00:00Z,2017-08-09T00:00:00Z,2017...",...,NaN,NaN,AllisonS,1429_1.csv,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
from lib.data_products_clean import clean_data_frame

df = clean_data_frame(df)
print(df.isna().sum())
display(df.sample(10))

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\agcor\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\agcor\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\agcor\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

name                 0
brand                0
asins                0
categories           0
manufacturer         0
reviews.date         0
reviews.username     0
primaryCategories    0
reviews.rating       0
reviews.text         0
reviews.title        0
all_categories       0
dtype: int64

,name,brand,asins,categories,manufacturer,reviews.date,reviews.username,primaryCategories,reviews.rating,reviews.text,reviews.title,all_categories
44915,AmazonBasics AAA Performance Alkaline Batterie...,Amazon Basics,"B00QWO9P0O,B00LH3DMUO",AA AAA Health Electronics Health Household Cam...,AmazonBasics,2017-01-11T00:00:00.000Z,Bymjsmommie333,Health Beauty,5.0,'ve buying batteries every size .... last long...,Great deal,AA AAA Health Electronics Health Household Cam...
62454,Fire Kids Edition Tablet 7 Display Wi-Fi 16 GB...,Amazon,B018Y22C2Y,Computers Fire Tablets Electronics Features Co...,Amazon,2017-02-16T00:00:00.000Z,Saejosh,Electronics,5.0,huge hit gift 3 year old daughter,real home run,Computers Fire Tablets Electronics Features Co...
56117,All-New Fire HD 8 Tablet 8 HD Display Wi-Fi 16...,Amazon,"B018SZT3BK,B01AHB9CN2",Fire Tablets Computers/Tablets Networking Elec...,Amazon,2016-12-23T00:00:00.000Z,Mayfield,Electronics,5.0,Great around Tablet little bit everything alon...,Kids love,Fire Tablets Computers/Tablets Networking Elec...
38675,All-New Fire HD 8 Tablet 8 '' HD Display Wi-Fi...,Amazon,B01AHB9CN2,Electronics iPad Tablets Tablets Fire Tablets ...,Amazon,2017-01-28T00:00:00.000Z,Tyree,Electronics,5.0,Bought daughter loves great product great price,Great tablet,Electronics iPad Tablets Tablets Fire Tablets ...
34799,Amazon Echo Show Alexa-enabled Bluetooth Speak...,Amazon,B010CEHQTG,Computers Amazon Echo Virtual Assistant Speake...,Amazon,2017-12-20T00:00:00.000Z,laf452,Electronics Hardware,4.0,bought two-for deal presents mother learning c...,Christmas presents mother son,Computers Amazon Echo Virtual Assistant Speake...
43628,AmazonBasics AAA Performance Alkaline Batterie...,Amazon Basics,"B00QWO9P0O,B00LH3DMUO",AA AAA Health Electronics Health Household Cam...,AmazonBasics,2017-07-26T00:00:00.000Z,ByKurt Kuhl Jr.,Health Beauty,4.0,Good Batteries,Four Stars,AA AAA Health Electronics Health Household Cam...
6644,Fire Tablet 7 Display Wi-Fi 8 GB Includes Spec...,Amazon,B018Y229OU,Fire Tablets Tablets Computers Tablets Tablets...,Amazon,2016-04-03T00:00:00.000Z,moonlite,,4.0,love far processes decent speed 've able need ...,Gd tablet,Fire Tablets Tablets Computers Tablets Tablets...
18683,Amazon Kindle Paperwhite eBook reader 4 GB 6 m...,Amazon,B00OQVZDJM,Walmart Business Office Electronics Tablets Of...,Amazon,2016-06-14T00:00:00.000Z,Newra,,5.0,Great battery life read especially like weight...,Works Great,Walmart Business Office Electronics Tablets Of...
10697,Fire Tablet 7 Display Wi-Fi 8 GB Includes Spec...,Amazon,B018Y229OU,Fire Tablets Tablets Computers Tablets Tablets...,Amazon,2016-01-05T00:00:00.000Z,Lally,,5.0,receiver seems pleased enjoys would buy,Bought gift someone new tablets,Fire Tablets Tablets Computers Tablets Tablets...
42384,AmazonBasics AAA Performance Alkaline Batterie...,Amazon Basics,"B00QWO9P0O,B00LH3DMUO",AA AAA Health Electronics Health Household Cam...,AmazonBasics,2016-09-02T00:00:00.000Z,ByAmazon Customer,Health Beauty,5.0,great,Five Stars,AA AAA Health Electronics Health Household Cam...

In [4]:
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(df, test_size=0.20, random_state=42)
train_df, val_df = train_test_split(train_df, test_size=0.10, random_state=42)

In [ ]:
MODEL_NAME = 'mabrouk/amazon-review-summarizer-bart'
MODEL_OUTPUT_DIR = "./models/bart-resumenes-finetuned"
MAX_INPUT_LENGTH = 512
MAX_TARGET_LENGTH = 64

In [ ]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)

c:\Users\agcor\Develop\ironhack_ai\7_Project3\project-automated-customers-reviews\.venv\Lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\agcor\.cache\huggingface\hub\models--mabrouk--amazon-review-summarizer-bart. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
[transformers] Please make sure the generation config includes `forced_bos_token_id=0`.
Loading weights: 100%|██████████| 515/515 [00:00<00:00, 25792.46it/s]

In [ ]:
def preprocess_function(df):
    inputs = df['reviews.title'] + " " + df["reviews.text"]
    targets = df["summary"]
 
    model_inputs = tokenizer(
        inputs,
        max_length=MAX_INPUT_LENGTH,
        truncation=True,
    )
 
    labels = tokenizer(
        text_target=targets,
        max_length=MAX_TARGET_LENGTH,
        truncation=True,
    )
 
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

In [ ]:
from datasets import Dataset, DatasetDict

datasets = DatasetDict({
    "train": Dataset.from_pandas(train_df.reset_index(drop=True)),
    "validation": Dataset.from_pandas(val_df.reset_index(drop=True)),
})

tokenized_datasets = datasets.map(
    preprocess_function,
    batched=True,
    remove_columns=datasets["train"].column_names,
)

In [ ]:
import evaluate
import numpy as np

rouge = evaluate.load("rouge")

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
 
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
 
    decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)
 
    result = rouge.compute(
        predictions=decoded_preds,
        references=decoded_labels,
        use_stemmer=True,
    )
    return {k: round(v, 4) for k, v in result.items()}

In [ ]:
from transformers import Seq2SeqTrainingArguments, Seq2SeqTrainer

training_args = Seq2SeqTrainingArguments(
    output_dir=MODEL_OUTPUT_DIR,
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    weight_decay=0.01,
    save_total_limit=2,
    num_train_epochs=3,
    predict_with_generate=True,
    fp16=True,
    load_best_model_at_end=True,
    metric_for_best_model="rougeL",
    logging_steps=50,
    report_to="none",
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

trainer.train()

In [ ]:
trainer.save_model(MODEL_OUTPUT_DIR)
tokenizer.save_pretrained(MODEL_OUTPUT_DIR)

In [ ]:
from transformers import pipeline
 
summarizer = pipeline(
    "summarization",
    model=MODEL_OUTPUT_DIR,
    tokenizer=MODEL_OUTPUT_DIR,
)

print(summarizer("Esto es un texto de prueba", max_length=60, min_length=10))