In [1]:
import os
import sys

project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root not in sys.path:
    sys.path.append(project_root)

In [2]:
GENERATED_SAMPLE_DATA_DIR = 'generated_sample_data'
OUTPUT_FILE_NAME = 'summarized_reviews.csv'

In [3]:
#if you need an API Key from OpenAI
#https://platform.openai.com/account/api-keys

from openai import OpenAI
from dotenv import load_dotenv, find_dotenv

_ = load_dotenv(find_dotenv(), override=True)

OPENAI_API_KEY  = os.getenv('OPENAI_API_KEY')

In [4]:
client = OpenAI(
    # This is the default and can be omitted
    api_key=OPENAI_API_KEY,
)

prompt = f"""
    You're an assistant that summarizes product reviews.
    Summarize the user review in about 2 or 3 sentences, \
    clearly and concisely, in english.
"""

system_prompt = { 'role': 'system', 'content': prompt }

def get_summarized_review(review, temperature=0):
    review_prompt = { 'role': 'user', 'content': review }
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[system_prompt, review_prompt],
        temperature=temperature,
    )

    return response.choices[0].message.content

In [5]:
from lib.data_load import load_data

df = await load_data()
print(f"\n{'CONCATENATED':<62} {df.shape[0]:>6,} rows x {df.shape[1]} cols")
df.sample(10)

1429_1.csv                                                     34,660 rows
Datafiniti_Amazon_Consumer_Reviews_of_Amazon_Products.csv       5,000 rows
Datafiniti_Amazon_Consumer_Reviews_of_Amazon_Products_May19.csv 28,332 rows

CONCATENATED                                                   67,992 rows x 28 cols

,id,name,asins,brand,categories,keys,manufacturer,reviews.date,reviews.dateAdded,reviews.dateSeen,...,reviews.userCity,reviews.userProvince,reviews.username,source_file,dateAdded,dateUpdated,primaryCategories,imageURLs,manufacturerNumber,sourceURLs
54646,AVpfw2hvilAPnD_xh0rH,"Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16...",B018Y226XO,Amazon,"Fire Tablets,Learning Toys,Toys,Tablets,Amazon...","amazon/53004754,841667103372,0841667103372,7in...",Amazon,2017-04-07T00:00:00.000Z,NaN,"2017-04-26T00:00:00Z,2017-05-10T00:00:00Z,2017...",...,NaN,NaN,Ashlee,Datafiniti_Amazon_Consumer_Reviews_of_Amazon_P...,2017-01-11T06:58:33Z,2019-03-09T07:13:43Z,"Toys & Games,Electronics",https://pisces.bbystatic.com/image2/BestBuy_US...,53-004754,http://www.toysrus.com/product/index.jsp?produ...
19801,AV1YnRtnglJLPUi8IJmV,Amazon Kindle Paperwhite - eBook reader - 4 GB...,B00OQVZDJM,Amazon,"Walmart for Business,Office Electronics,Tablet...","amazon/b00oqvzdjm,848719056099,amazonkindlepap...",Amazon,2017-08-11T00:00:00.000Z,2017-09-05T22:09:30Z,2017-08-31T22:33:01.361Z,...,NaN,NaN,1EWG,1429_1.csv,NaN,NaN,NaN,NaN,NaN,NaN
43310,AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,"B00QWO9P0O,B00LH3DMUO",Amazonbasics,"AA,AAA,Health,Electronics,Health & Household,C...","amazonbasics/hl002619,amazonbasicsaaaperforman...",AmazonBasics,2016-01-22T00:00:00.000Z,NaN,2017-08-28T00:00:00Z,...,NaN,NaN,ByJeffrey Sponseller,Datafiniti_Amazon_Consumer_Reviews_of_Amazon_P...,2015-10-30T08:59:32Z,2019-04-25T09:08:16Z,Health & Beauty,https://images-na.ssl-images-amazon.com/images...,HL-002619,"https://www.barcodable.com/upc/841710106442,ht..."
65982,AVqkIhxunnc1JgDc3kg_,"Fire HD 8 Tablet with Alexa, 8 HD Display, 16 ...",B018T075DC,Amazon,"Fire Tablets,Tablets,All Tablets,Amazon Tablet...","amazon/b018t075dc,firehd8tabletwithalexa8hddis...",Amazon,2017-01-23T00:00:00.000Z,NaN,"2017-04-30T00:00:00Z,2017-06-07T00:00:00Z",...,NaN,NaN,bobs88,Datafiniti_Amazon_Consumer_Reviews_of_Amazon_P...,2017-03-06T14:59:43Z,2019-02-23T02:49:38Z,Electronics,https://www.upccodesearch.com/images/barcode/0...,53-004485,http://reviews.bestbuy.com/3545/5620410/review...
56433,AVpfw2hvilAPnD_xh0rH,"Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16...",B018Y226XO,Amazon,"Fire Tablets,Learning Toys,Toys,Tablets,Amazon...","amazon/53004754,841667103372,0841667103372,7in...",Amazon,2017-02-03T00:00:00.000Z,NaN,"2017-04-26T00:00:00Z,2017-05-10T00:00:00Z,2017...",...,NaN,NaN,Buckos69,Datafiniti_Amazon_Consumer_Reviews_of_Amazon_P...,2017-01-11T06:58:33Z,2019-03-09T07:13:43Z,"Toys & Games,Electronics",https://pisces.bbystatic.com/image2/BestBuy_US...,53-004754,http://www.toysrus.com/product/index.jsp?produ...
41696,AVpgNzjwLJeJML43Kpxn,AmazonBasics AAA Performance Alkaline Batterie...,"B00QWO9P0O,B00LH3DMUO",Amazonbasics,"AA,AAA,Health,Electronics,Health & Household,C...","amazonbasics/hl002619,amazonbasicsaaaperforman...",AmazonBasics,2015-12-21T00:00:00.000Z,NaN,2017-08-28T00:00:00Z,...,NaN,NaN,ByR. Catalano,Datafiniti_Amazon_Consumer_Reviews_of_Amazon_P...,2015-10-30T08:59:32Z,2019-04-25T09:08:16Z,Health & Beauty,https://images-na.ssl-images-amazon.com/images...,HL-002619,"https://www.barcodable.com/upc/841710106442,ht..."
56492,AVpfw2hvilAPnD_xh0rH,"Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16...",B018Y226XO,Amazon,"Fire Tablets,Learning Toys,Toys,Tablets,Amazon...","amazon/53004754,841667103372,0841667103372,7in...",Amazon,2016-08-19T00:00:00.000Z,NaN,"2017-03-21T00:00:00Z,2017-03-05T00:00:00Z,2017...",...,NaN,NaN,senia863,Datafiniti_Amazon_Consumer_Reviews_of_Amazon_P...,2017-01-11T06:58:33Z,2019-03-09T07:13:43Z,"Toys & Games,Electronics",https://pisces.bbystatic.com/image2/BestBuy_US...,53-004754,http://www.toysrus.com/product/index.jsp?produ...
22933,AVpfl8cLLJeJML43AE3S,"Echo (White),,,\r\nEcho (White),,,","B00L9EPT8O,B01E6AO69U",Amazon,"Stereos,Remote Controls,Amazon Echo,Audio Dock...","echowhite/263039693056,echowhite/152558276095,...",Amazon,2016-12-31T00:00:00.000Z,NaN,"2017-09-28T00:00:00Z,2017-09-08T00:00:00Z,2017...",...,NaN,NaN,TitanItUp,1429_1.csv,NaN,NaN,NaN,NaN,NaN,NaN
39368,AVpftoij1cnluZ0-p5n2,Amazon - Kindle Voyage - 4GB - Wi-Fi + 3G - Black,B00IOYAM4I,Amazon,"Computers & Tablets,E-Readers & Accessories,eB...","amazonkindlevoyage4gbwifi3gblack/9301112,amazo...",Amazon,2015-09-18T00:00:00.000Z,2017-09-19T15:09:00Z,"2017-09-09T09:54:00.000Z,2017-08-31T22:37:00.0...",...,NaN,NaN,philipsmom,Datafiniti_Amazon_Consumer_Reviews_of_Amazon_P...,2015-12-02T05:30:10Z,2017-09-25T00:50:28Z,Electronics,https://pisces.bbystatic.com/image2/BestBuy_US...,B00IOYAM4I,https://www.bestbuy.com/site/amazon-kindle-voy...
50072,AVpe7xlELJeJML43ypLz,AmazonBasics AA Performance Alkaline Batteries...,"B00QWO9P0O,B01IB83NZG,B00MNV8E0C",Amazonbasics,"AA,AAA,Electronics Features,Health,Electronics...",amazonbasicsaaperformancealkalinebatteries48co...,AmazonBasics,2016-03-23T00:00:00.000Z,NaN,2017-06-28T00:00:00Z,...,NaN,NaN,ByPaddywhack,Datafiniti_Amazon_Consumer_Reviews_of_Amazon_P...,2015-12-03T01:23:41Z,2019-04-24T02:17:42Z,Health & Beauty,https://images-na.ssl-images-amazon.com/images...,LR6G0748FFPAB-US,"https://www.barcodable.com/upc/841710106411,ht..."

In [6]:
from lib.data_products_clean import clean_data_frame

df = clean_data_frame(df)
print(df.isna().sum())
display(df.sample(10))

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\agcor\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\agcor\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\agcor\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

name                 0
brand                0
asins                0
categories           0
manufacturer         0
reviews.date         0
reviews.username     0
primaryCategories    0
reviews.rating       0
reviews.text         0
reviews.title        0
all_categories       0
dtype: int64

,name,brand,asins,categories,manufacturer,reviews.date,reviews.username,primaryCategories,reviews.rating,reviews.text,reviews.title,all_categories
55260,All-New Fire HD 8 Tablet 8 HD Display Wi-Fi 16...,Amazon,"B018SZT3BK,B01AHB9CN2",Fire Tablets Computers/Tablets Networking Elec...,Amazon,2017-01-19T00:00:00.000Z,JonE,Electronics,4.0,Gift son really enjoying read well play games,Great starter tablet,Fire Tablets Computers/Tablets Networking Elec...
21029,Amazon Fire Hd 8 8in Tablet 16gb Black B018szt...,Amazon,B00IOY8XWQ,Walmart Business Office Electronics Tablets El...,Amazon,2016-02-27T00:00:00.000Z,KenNS,,4.0,Extra features nice upgrading Kindle Paperwhit...,Nice Upgrade,Walmart Business Office Electronics Tablets El...
65782,Fire HD 8 Tablet Alexa 8 HD Display 16 GB Tang...,Amazon,B018T075DC,Fire Tablets Tablets Tablets Amazon Tablets Ge...,Amazon,2016-12-07T00:00:00.000Z,odalmasi,Electronics,5.0,excellent tablet price wonderfull great perfor...,cheap tablet great,Fire Tablets Tablets Tablets Amazon Tablets Ge...
48137,AmazonBasics AA Performance Alkaline Batteries...,Amazon Basics,"B00QWO9P0O,B01IB83NZG,B00MNV8E0C",AA AAA Electronics Features Health Electronics...,AmazonBasics,2016-10-08T00:00:00.000Z,ByKevin,Health Beauty,5.0,AmazonBasics AAA Performance Alkaline Batterie...,AmazonBasics AAA Performance Alkaline Batterie...,AA AAA Electronics Features Health Electronics...
8055,Fire Tablet 7 Display Wi-Fi 8 GB Includes Spec...,Amazon,B018Y229OU,Fire Tablets Tablets Computers Tablets Tablets...,Amazon,2016-12-14T00:00:00.000Z,Adrian,,5.0,great tablet price regret n't buy another one ...,Great,Fire Tablets Tablets Computers Tablets Tablets...
24669,Echo White Echo White,Amazon,"B00L9EPT8O,B01E6AO69U",Stereos Remote Controls Amazon Echo Audio Dock...,Amazon,2016-11-25T00:00:00.000Z,Ohio1947,,5.0,Purchased grandson everyone house enjoys,Best birthday gift ever,Stereos Remote Controls Amazon Echo Audio Dock...
21831,Echo White Echo White,Amazon,B00TSUGXKE,Electronics Features Fire Tablets Computers Ta...,Amazon,2017-07-21T00:00:00.000Z,MrsMaree,,5.0,Purchased 7 year old grandson loves easy use,Great grandson,Electronics Features Fire Tablets Computers Ta...
38143,All-New Fire HD 8 Tablet 8 '' HD Display Wi-Fi...,Amazon,B01AHB9CN2,Electronics iPad Tablets Tablets Fire Tablets ...,Amazon,2017-01-23T00:00:00.000Z,truckguru,Electronics,5.0,love Fire HD Went back bought Fire 7 '' wife a...,Great buy,Electronics iPad Tablets Tablets Fire Tablets ...
56643,All-New Fire HD 8 Tablet 8 HD Display Wi-Fi 32...,Amazon,B01ACEKAJY,Fire Tablets Computers/Tablets Networking Tabl...,Amazon,2017-05-20T00:00:00.000Z,shopstoomuch,Electronics,5.0,husband 's previous tablet died sudden death g...,Nice tablet great price,Fire Tablets Computers/Tablets Networking Tabl...
24887,Amazon 9W PowerFast Official OEM USB Charger P...,Amazon,"B00L9EPT8O,B01E6AO69U",Stereos Remote Controls Amazon Echo Audio Dock...,Amazon,2016-12-15T00:00:00.000Z,ralphv,,5.0,got gift happy like music demand much Thanks h...,believe unit,Stereos Remote Controls Amazon Echo Audio Dock...

In [7]:
df['reviews.content'] = df['reviews.title'] + " " + df['reviews.text']
df['reviews.summary'] = df['reviews.content'].apply(get_summarized_review)
display(df.sample(10))

RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for gpt-3.5-turbo in organization org-IUbHmy0GSm3fGL8T9247x1sw on requests per day (RPD): Limit 10000, Used 10000, Requested 1. Please try again in 8.64s. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'requests', 'param': None, 'code': 'rate_limit_exceeded'}}

In [8]:
# Save summarized reviews into CSV
df.to_csv(os.path.join(GENERATED_SAMPLE_DATA_DIR, OUTPUT_FILE_NAME), index=False)